name: lhd-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core Python
  - python=3.10
  - pip
  - setuptools<70

  # Scientific & GIS Packages (from conda-forge for stability)
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - xarray
  - rasterio
  - requests
  - scipy
  - openpyxl
  - gdal
  - laspy
  - contextily
  - dask
  - distributed
  - pyproj
  - fiona
  - shapely
  - s3fs
  - tqdm

  # External Packages (installed via pip from GitHub)
  - pip:
    - geoglows
    - teehr
    - pyarrow
    - matplotlib_scalebar
    - hsclient
    - lazrs
    - git+https://github.com/jlgutenson/rathcelon.git
    - git+https://github.com/MikeFHS/automated-rating-curve.git

  - pynhd
  - py3dep
  - hydrosignatures
  - pygeohydro