name: lhd-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core Python
  - python=3.10
  - pip
  - setuptools<70

  # Scientific & GIS Packages (from conda-forge for stability)
  - geopandas
  - matplotlib
  - numpy<2.0
  - pandas
  - xarray
  - rasterio
  - requests
  - scipy
  - openpyxl
  - gdal
  - contextily
  - dask
  - distributed
  - pyproj=3.6.1
  - fiona
  - shapely
  - s3fs
  - tqdm

  # External Packages (installed via pip from GitHub)
  - pip:
    - geoglows
    - teehr
    - pyarrow
    - matplotlib_scalebar
    - hsclient
    - laspy
    - lazrs
    - pynhd
    - py3dep
    - hydrosignatures
    - pygeohydro
    - nest-asyncio